/// <reference types="vite/client" />

/**
 * App version, inlined by Vite from `package.json` at build time (see `vite.config.ts`).
 * Declared here so TypeScript knows about the global that `define` injects.
 */
declare const __APP_VERSION__: string;

/**
 * Entity sprites found under `public/images/entities`, generated by the `entity-images` plugin
 * in `vite.config.ts` and read through `services/entityImageService.ts`.
 *
 * Keyed by `<category>/<entity id>`, where the category is the folder the sprites live in
 * (`characters` or `mobs`). Entities without sprites are absent from the map.
 */
declare module 'virtual:entity-images' {
    import type { EntityImage } from './types/EntityImageType';

    export const entityImages: Record<string, EntityImage[]>;
}
